apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: prod
namePrefix: prod-

images:
- name: aneeswar/notes-app
  newName: aneeswar/notes-app
  newTag: latest

patches:
- target:
    kind: Ingress
    name: notes-app-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: prod.noteops.local
- target:
    kind: Rollout
    name: notes-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2

commonAnnotations:
  argocd-image-updater.argoproj.io/image-list: notes-app=aneeswar/notes-app
  argocd-image-updater.argoproj.io/notes-app.update-strategy: latest
  argocd-image-updater.argoproj.io/write-back-method: git
