replicaCount: 1

image:
  repository: aneeswar/notes-app
  pullPolicy: IfNotPresent
  tag: 608bdc3

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
